# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_remove_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='date_loaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
