# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_parcel_date_loaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='date_loaded',
            new_name='loaded_on',
        ),
        migrations.AddField(
            model_name='parcel',
            name='collected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Loading'), (1, 'Transit'), (2, 'Arrived'), (3, 'Collected')]),
        ),
    ]
