# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_entry_current_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='kegs',
            field=models.BooleanField(default=False),
        ),
    ]
