# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0004_auto_20160509_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='num_cars',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '1 - 10'), (1, '11 - 20'), (2, '> 20')], null=True),
        ),
    ]
