# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0006_auto_20160513_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the state in small letters and with spaces changed to _'),
        ),
    ]
