# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0007_state_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Google Place ID'),
        ),
        migrations.AlterField(
            model_name='station',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
