# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heathen', '0004_auto_20161128_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
