# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('licence_no', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date_of_payment', models.DateField()),
                ('expiration_date', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.Business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.BusinessType'),
        ),
    ]
