# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='regitration_date',
            new_name='registration_date',
        ),
    ]
