# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0003_auto_20160531_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
