# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0004_drug_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='uuid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
