# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0005_auto_20160531_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('when', models.DateTimeField(default=datetime.datetime.now)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugshare.Pharmacy')),
            ],
        ),
    ]
