# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0006_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('posted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Cancelled'), (2, 'Accepted'), (3, 'Done')], default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugshare.Drug')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugshare.Pharmacy')),
            ],
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
