# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0008_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='new_status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Cancelled'), (2, 'Accepted'), (3, 'Done')]),
        ),
    ]
