# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0009_auto_20160602_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='uuid',
            field=models.CharField(max_length=200),
        ),
    ]
