# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0011_pharmacy_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
