# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0013_auto_20160604_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
