# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0014_pharmacy_pharmacist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='area',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='street',
        ),
    ]
