# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0015_auto_20160606_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='state',
        ),
        migrations.AddField(
            model_name='outlet',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugshare.Pharmacy'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drugshare.State'),
        ),
    ]
