# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0021_auto_20160609_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='uuid',
        ),
    ]
