# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0022_remove_pharmacy_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
