# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0023_device_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugrequest',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='drugrequest',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugshare.Outlet'),
        ),
    ]
