# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0024_auto_20160609_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
