# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugshare', '0025_pharmacy_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('when', models.DateField(default=datetime.date.today)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugshare.Pharmacy')),
            ],
        ),
    ]
