# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.BloodType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Location')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Subscriber')),
            ],
        ),
    ]
