# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0004_auto_20161202_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.BloodRequest')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Subscriber')),
            ],
        ),
    ]
