# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-03 20:01
from __future__ import unicode_literals

from django.db import migrations


def make_candidates(apps, schema_editor):
    Candidate = apps.get_model('medic', 'Candidate')
    BloodRequest = apps.get_model('medic', 'BloodRequest')
    for req in BloodRequest.objects.all():
        Candidate.objects.create(
            blood_request=req,
            subscriber=req.subscriber,
            active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0005_candidate'),
    ]

    operations = [
        migrations.RunPython(make_candidates),
    ]
