# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0006_auto_20161203_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
