# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-05 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0007_bloodrequest_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
