# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('building_type', models.CharField(blank=True, max_length=200)),
                ('consultants', models.CharField(blank=True, max_length=200)),
                ('contractors', models.CharField(blank=True, max_length=200)),
                ('insurance_type', models.CharField(blank=True, max_length=200)),
                ('rep', models.CharField(blank=True, max_length=200, verbose_name='Representative')),
                ('foreman', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('height', models.CharField(blank=True, max_length=200)),
                ('basement', models.CharField(blank=True, max_length=200)),
                ('floors', models.CharField(blank=True, max_length=200)),
                ('building', models.ImageField(upload_to='pictures', verbose_name='Building Image')),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
