# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insure.Device'),
        ),
        migrations.AddField(
            model_name='entry',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
