# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insure', '0002_auto_20160528_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approval_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
