# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(max_length=50)),
                ('booked_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
