# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20160619_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('msisdn', models.CharField(max_length=20)),
            ],
        ),
    ]
