# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20160619_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Resident'),
        ),
    ]
