# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('when', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(default=datetime.date.today)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Resident')),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagetopup',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Estate'),
        ),
    ]
