# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160619_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
